// This file has been autogenerated from a class added in the UI designer.
using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;
using System.Diagnostics;
using PayPalMobileForXamarin;

namespace PayPalMobileSample2
{
    public partial class FlipsideViewController : UIViewController
    {
        public FlipsideViewController (IntPtr handle) : base (handle)
        {
        }

        public PayPalMobileSample2ViewController Parent { get; set; }

        public override void AwakeFromNib ()
        {
            this.ContentSizeForViewInPopover = new SizeF (320, 480);
            base.AwakeFromNib ();
        }

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();
        }

        void LogEnvironment ()
        {
            Debug.WriteLine ("Environment: {0}. Accept credit cards? {1}", this.Parent.Environment, this.Parent.AcceptCreditCards);
        }

        public override void ViewWillAppear (bool animated)
        {
            base.ViewWillAppear (animated);

            this.LogEnvironment ();

            if (PayPalPaymentDelegate.PayPalEnvironmentProduction == this.Parent.Environment) {
                this.environmentSegmentedControl.SelectedSegment = 2;
            } else if (PayPalPaymentDelegate.PayPalEnvironmentSandbox == this.Parent.Environment) {
                this.environmentSegmentedControl.SelectedSegment = 1;
            } else if (PayPalPaymentDelegate.PayPalEnvironmentNoNetwork == this.Parent.Environment) {
                this.environmentSegmentedControl.SelectedSegment = 0;
            }

            this.acceptCreditCards.On = this.Parent.AcceptCreditCards;

            if (this.Parent.CompletedPayment != null) {
                Debug.WriteLine (this.Parent.CompletedPayment.ToString());
                this.proofOfPaymentTextView.Text = this.Parent.CompletedPayment.ToString();
            } else {
                this.proofOfPaymentTextView.Hidden = true;
                this.proofOfPaymentLabel.Hidden = true;
            }
            this.proofOfPaymentTextView.Layer.CornerRadius = 8.0f;

        }

        public override void DidReceiveMemoryWarning ()
        {
            // Releases the view if it doesn't have a superview.
            base.DidReceiveMemoryWarning ();

            // Release any cached data, images, etc that aren't in use.
        }

        partial void environmentControlDidUpdate (NSObject sender)
        {
            switch (this.environmentSegmentedControl.SelectedSegment) {
            case 0:
                this.Parent.Environment = PayPalPaymentDelegate.PayPalEnvironmentNoNetwork;
                break;
            case 1:
                this.Parent.Environment = PayPalPaymentDelegate.PayPalEnvironmentSandbox;
                break;
            default:
                this.Parent.Environment = PayPalPaymentDelegate.PayPalEnvironmentProduction;
                break;
            }

            this.LogEnvironment ();
        }

        partial void processCreditCardsChanged (NSObject sender)
        {
            this.Parent.AcceptCreditCards = this.acceptCreditCards.On;
            this.LogEnvironment ();
        }

        partial void actDone (NSObject sender)
        {
            this.LogEnvironment ();
            this.Parent.FlipsideViewControllerDidFinish(this);
        }
    }
}
